name: "Lock inactive closed issues and PRs"

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:
    inputs: {}

jobs:
  lock:
    uses: "orisai/github-workflows/.github/workflows/lock-closed-threads.yaml@v1"
